import React, { useState } from 'react';
import { LawyerConsultationDossier } from '../types';
import { 
  Briefcase, 
  AlertOctagon, 
  HelpCircle, 
  Ban, 
  Copy, 
  Check, 
  FileText,
  ShieldCheck,
  ArrowRight
} from 'lucide-react';

interface AttorneyDossierProps {
  dossier: LawyerConsultationDossier;
  docTitle: string;
  fairnessIndex: number;
  disclaimer: string;
}

export const AttorneyDossier: React.FC<AttorneyDossierProps> = ({
  dossier,
  docTitle,
  fairnessIndex,
  disclaimer
}) => {
  const [copiedQuestionIdx, setCopiedQuestionIdx] = useState<number | null>(null);
  const [copiedFullBrief, setCopiedFullBrief] = useState(false);

  const handleCopyQuestion = (question: string, idx: number) => {
    navigator.clipboard.writeText(question);
    setCopiedQuestionIdx(idx);
    setTimeout(() => setCopiedQuestionIdx(null), 2000);
  };

  const handleCopyFullBrief = () => {
    const brief = `# ATTORNEY CONSULTATION BRIEFING
Generated by Lexisense Legal Intelligence Engine
Document: ${docTitle}
Document Fairness Index: ${fairnessIndex}/100

## 1. TOP RED FLAGS FOR DISCUSSION
${dossier.top_red_flags_for_discussion.map((rf, i) => `${i + 1}. ${rf}`).join('\n')}

## 2. HIGH-LEVERAGE QUESTIONS FOR COUNSEL
${dossier.high_leverage_questions_for_counsel.map((q, i) => `${i + 1}. ${q}`).join('\n')}

## 3. SUGGESTED WALKAWAY TERMS
${dossier.suggested_walkaway_terms.map((w, i) => `- ${w}`).join('\n')}

---
${disclaimer}
`;
    navigator.clipboard.writeText(brief);
    setCopiedFullBrief(true);
    setTimeout(() => setCopiedFullBrief(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Header card with action */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-indigo-500/10 border border-indigo-500/30 flex items-center justify-center text-indigo-400 shrink-0">
            <Briefcase className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-semibold text-white font-['Cinzel',serif]">
              Attorney Consultation Briefing Dossier
            </h3>
            <p className="text-xs text-slate-400">
              Designed to optimize billable legal consultation hours with targeted high-leverage inquiries and non-negotiable walkaways.
            </p>
          </div>
        </div>

        <button
          id="btn-copy-full-brief"
          onClick={handleCopyFullBrief}
          className="flex items-center gap-1.5 px-3.5 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold shadow-sm transition cursor-pointer self-start md:self-auto shrink-0"
        >
          {copiedFullBrief ? (
            <>
              <Check className="w-3.5 h-3.5" />
              <span>Copied Briefing to Clipboard</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5" />
              <span>Copy Full Attorney Dossier</span>
            </>
          )}
        </button>
      </div>

      {/* 1. Top Red Flags */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
        <div className="flex items-center gap-2">
          <AlertOctagon className="w-4 h-4 text-red-400" />
          <h4 className="text-sm font-semibold uppercase tracking-wider text-red-400 font-sans">
            Top Priority Red Flags for Legal Review
          </h4>
        </div>
        <div className="space-y-2.5">
          {dossier.top_red_flags_for_discussion.map((flag, idx) => (
            <div
              key={idx}
              className="p-3 rounded-lg bg-slate-950/70 border border-red-500/20 text-xs text-slate-200 flex items-start gap-3"
            >
              <span className="w-5 h-5 rounded-full bg-red-500/20 text-red-300 font-mono font-bold flex items-center justify-center shrink-0 mt-0.5">
                {idx + 1}
              </span>
              <span className="leading-relaxed font-sans">{flag}</span>
            </div>
          ))}
        </div>
      </div>

      {/* 2. High-Leverage Questions for Counsel */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <HelpCircle className="w-4 h-4 text-amber-400" />
            <h4 className="text-sm font-semibold uppercase tracking-wider text-amber-400 font-sans">
              High-Leverage Questions for Attorney Billing Session
            </h4>
          </div>
          <span className="text-[11px] text-slate-400">Click to copy individual question</span>
        </div>

        <div className="space-y-3">
          {dossier.high_leverage_questions_for_counsel.map((question, idx) => (
            <div
              key={idx}
              className="p-3.5 rounded-lg bg-slate-950/70 border border-slate-800 hover:border-slate-700 text-xs text-slate-200 flex items-start justify-between gap-4 transition group"
            >
              <div className="flex items-start gap-3">
                <span className="w-5 h-5 rounded-full bg-amber-500/20 text-amber-300 font-mono font-bold flex items-center justify-center shrink-0 mt-0.5">
                  Q{idx + 1}
                </span>
                <span className="leading-relaxed font-sans text-slate-100 font-medium">{question}</span>
              </div>

              <button
                id={`copy-q-${idx}`}
                onClick={() => handleCopyQuestion(question, idx)}
                className="opacity-80 group-hover:opacity-100 p-1.5 rounded hover:bg-slate-800 text-slate-400 hover:text-amber-300 transition cursor-pointer shrink-0"
                title="Copy Question"
              >
                {copiedQuestionIdx === idx ? (
                  <Check className="w-4 h-4 text-emerald-400" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* 3. Suggested Walkaway Terms */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
        <div className="flex items-center gap-2">
          <Ban className="w-4 h-4 text-rose-400" />
          <h4 className="text-sm font-semibold uppercase tracking-wider text-rose-400 font-sans">
            Recommended Walkaway Terms (Dealbreaker Thresholds)
          </h4>
        </div>
        <p className="text-xs text-slate-400">
          If the counterparty refuses to amend or strike these specific clauses, execution carries severe asymmetric operational risk.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {dossier.suggested_walkaway_terms.map((term, idx) => (
            <div
              key={idx}
              className="p-3.5 rounded-lg bg-slate-950/80 border border-rose-900/40 text-xs text-slate-200 flex items-start gap-2.5"
            >
              <span className="w-2 h-2 rounded-full bg-rose-500 mt-1.5 shrink-0" />
              <span className="leading-relaxed">{term}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Statutory Disclaimer Box */}
      <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-400 leading-relaxed text-center">
        <strong className="text-slate-300 block mb-1">Lexisense Statutory Boundary Notice</strong>
        {disclaimer}
      </div>
    </div>
  );
};
