/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { LawyerConsultationDossier } from '../types';
import { 
  Briefcase, 
  AlertOctagon, 
  HelpCircle, 
  Ban, 
  Copy, 
  Check, 
  FileText,
  ShieldCheck,
  ArrowRight,
  Pin,
  Trash2,
  ExternalLink,
  MessageSquare,
  Sparkles,
  ChevronRight,
  Bot,
  Flame,
  Shield,
  Scale
} from 'lucide-react';
import { 
  PinnedDossierItem, 
  DossierPriority 
} from '../utils/pinnedDossierTracker';
import { getClauseToneSentiment } from '../utils/clauseToneAnalyzer';
import { AskAttorneyChat } from './AskAttorneyChat';

interface AttorneyDossierProps {
  dossier: LawyerConsultationDossier;
  docTitle: string;
  fairnessIndex: number;
  disclaimer: string;
  partyFavored?: string;
  pinnedItems?: Record<string, PinnedDossierItem>;
  onUpdateNote?: (clauseId: string, note: string) => void;
  onUpdatePriority?: (clauseId: string, priority: DossierPriority) => void;
  onRemoveItem?: (clauseId: string) => void;
  onNavigateToClause?: (clauseId: string) => void;
  onOpenSidebar?: () => void;
}

export const AttorneyDossier: React.FC<AttorneyDossierProps> = ({
  dossier,
  docTitle,
  fairnessIndex,
  disclaimer,
  partyFavored = 'Counterparty',
  pinnedItems = {},
  onUpdateNote,
  onUpdatePriority,
  onRemoveItem,
  onNavigateToClause,
  onOpenSidebar
}) => {
  const [activeDossierSubTab, setActiveDossierSubTab] = useState<'briefing' | 'chat'>('briefing');
  const [copiedQuestionIdx, setCopiedQuestionIdx] = useState<number | null>(null);
  const [copiedFullBrief, setCopiedFullBrief] = useState(false);
  const [editingNoteId, setEditingNoteId] = useState<string | null>(null);
  const [tempNote, setTempNote] = useState<string>('');

  const curatedList = Object.values(pinnedItems).sort((a, b) => b.pinnedAt - a.pinnedAt);

  const handleCopyQuestion = (question: string, idx: number) => {
    navigator.clipboard.writeText(question);
    setCopiedQuestionIdx(idx);
    setTimeout(() => setCopiedQuestionIdx(null), 2000);
  };

  const handleCopyFullBrief = () => {
    const curatedSection = curatedList.length > 0 ? [
      '',
      `## CLIENT CURATED CLAUSE POINTS & NEGOTIATION OBJECTIVES (${curatedList.length} CLAUSES)`,
      ...curatedList.map((item, idx) => {
        const priorityLabel = 
          item.priority === 'HIGH_PRIORITY' ? 'HIGH PRIORITY' :
          item.priority === 'WALKAWAY' ? 'DEALBREAKER / WALKAWAY' :
          item.priority === 'REDLINE' ? 'REDLINE COUNTER-OFFER' :
          'CLARIFICATION FOR COUNSEL';
        return [
          `### ${idx + 1}. [${item.clause.clause_id}] ${item.clause.clause_category} - ${priorityLabel}`,
          `- Risk Assessment: ${item.clause.risk_level} (Favors: ${item.clause.party_favored})`,
          item.customNote ? `- Client Consultation Objective: "${item.customNote}"` : null,
          `- Verbatim Extract: "${item.clause.verbatim_quote}"`,
          `- Proposed Redline: "${item.workingRedline || item.clause.proposed_redline}"`,
          ''
        ].filter(Boolean).join('\n');
      })
    ].join('\n') : '';

    const brief = `# ATTORNEY CONSULTATION BRIEFING
Generated by Lexisense Legal Intelligence Engine
Document: ${docTitle}
Document Fairness Index: ${fairnessIndex}/100
${curatedSection}

## 1. TOP RED FLAGS FOR DISCUSSION
${dossier.top_red_flags_for_discussion.map((rf, i) => `${i + 1}. ${rf}`).join('\n')}

## 2. HIGH-LEVERAGE QUESTIONS FOR COUNSEL
${dossier.high_leverage_questions_for_counsel.map((q, i) => `${i + 1}. ${q}`).join('\n')}

## 3. SUGGESTED WALKAWAY TERMS
${dossier.suggested_walkaway_terms.map((w, i) => `- ${w}`).join('\n')}

---
${disclaimer}
`;
    navigator.clipboard.writeText(brief);
    setCopiedFullBrief(true);
    setTimeout(() => setCopiedFullBrief(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Header card with action */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-indigo-500/10 border border-indigo-500/30 flex items-center justify-center text-indigo-400 shrink-0">
            <Briefcase className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white font-['Cinzel',serif]">
                Attorney Consultation Briefing Dossier
              </h3>
              {curatedList.length > 0 && (
                <span className="font-mono text-xs px-2 py-0.5 rounded-full bg-amber-500/20 text-amber-300 border border-amber-500/40 font-semibold">
                  {curatedList.length} Curated Points
                </span>
              )}
            </div>
            <p className="text-xs text-slate-400">
              Designed to optimize billable legal consultation hours with your curated clauses, targeted high-leverage inquiries, and non-negotiable walkaways.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 self-start md:self-auto shrink-0">
          {onOpenSidebar && (
            <button
              type="button"
              id="btn-open-sidebar-from-dossier"
              onClick={onOpenSidebar}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-slate-800 hover:bg-slate-750 text-slate-200 text-xs font-semibold border border-slate-700 transition cursor-pointer"
            >
              <Pin className="w-3.5 h-3.5 text-amber-400" />
              <span>Curated Tray ({curatedList.length})</span>
            </button>
          )}

          <button
            id="btn-copy-full-brief"
            onClick={handleCopyFullBrief}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold shadow-sm transition cursor-pointer"
          >
            {copiedFullBrief ? (
              <>
                <Check className="w-3.5 h-3.5" />
                <span>Copied Briefing to Clipboard</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Full Attorney Dossier</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Mode Navigation Sub-Tabs */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-2">
        <div className="flex items-center gap-2">
          <button
            type="button"
            id="subtab-briefing-dossier"
            onClick={() => setActiveDossierSubTab('briefing')}
            className={`px-3.5 py-2 rounded-lg text-xs font-semibold flex items-center gap-2 transition cursor-pointer border ${
              activeDossierSubTab === 'briefing'
                ? 'bg-slate-800 text-amber-300 border-slate-700 shadow-sm'
                : 'text-slate-400 hover:text-slate-200 border-transparent'
            }`}
          >
            <Briefcase className="w-3.5 h-3.5 text-amber-400" />
            <span>Consultation Briefing & Curated Clauses ({curatedList.length})</span>
          </button>

          <button
            type="button"
            id="subtab-ask-attorney"
            onClick={() => setActiveDossierSubTab('chat')}
            className={`px-3.5 py-2 rounded-lg text-xs font-semibold flex items-center gap-2 transition cursor-pointer border ${
              activeDossierSubTab === 'chat'
                ? 'bg-amber-500/20 text-amber-200 border-amber-500/50 shadow-sm'
                : 'text-slate-400 hover:text-slate-200 border-transparent'
            }`}
          >
            <Bot className="w-3.5 h-3.5 text-amber-400" />
            <span>Ask the Attorney AI</span>
            <span className="text-[10px] px-1.5 py-0.2 rounded font-mono font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
              Gemini
            </span>
          </button>
        </div>
      </div>

      {activeDossierSubTab === 'chat' ? (
        <div className="h-[650px]">
          <AskAttorneyChat
            pinnedItems={pinnedItems}
            docTitle={docTitle}
            dfiScore={fairnessIndex}
            partyFavored={partyFavored}
            onAppendNoteToClause={onUpdateNote}
            className="h-full"
          />
        </div>
      ) : (
        <>

      {/* 0. User Curated Consultation Collection Section */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-md bg-amber-500/10 border border-amber-500/30 flex items-center justify-center text-amber-400">
              <Pin className="w-4 h-4" />
            </div>
            <div>
              <h4 className="text-sm font-semibold uppercase tracking-wider text-amber-400 font-sans">
                Curated Clause Points for Legal Consultation ({curatedList.length})
              </h4>
              <p className="text-xs text-slate-400">
                Clauses specifically pinned from your audit cards for focused discussion during counsel review.
              </p>
            </div>
          </div>

          {onOpenSidebar && (
            <button
              type="button"
              onClick={onOpenSidebar}
              className="text-xs font-medium text-amber-400 hover:text-amber-300 transition cursor-pointer flex items-center gap-1 hover:underline"
            >
              <span>Manage Tray</span>
              <ChevronRight className="w-3.5 h-3.5" />
            </button>
          )}
        </div>

        {curatedList.length === 0 ? (
          <div className="p-6 rounded-lg bg-slate-950/60 border border-dashed border-slate-800 text-center space-y-2">
            <Pin className="w-6 h-6 text-slate-600 mx-auto" />
            <p className="text-xs font-semibold text-slate-300">No Clauses Pinned Yet</p>
            <p className="text-xs text-slate-500 max-w-md mx-auto">
              Browse the <strong className="text-slate-400">Clause Audit Cards</strong> or <strong className="text-slate-400">Dual-Pane Citation Inspector</strong> and click <strong className="text-amber-400">"Pin to Dossier"</strong> to curate specific provisions for your legal counsel meeting.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            {curatedList.map((item) => (
              <div
                key={item.clauseId}
                id={`curated-clause-${item.clauseId}`}
                className="bg-slate-950/80 border border-slate-800/90 hover:border-slate-700 rounded-xl p-4 space-y-3 transition flex flex-col justify-between"
              >
                <div className="space-y-2.5">
                  <div className="flex items-center justify-between gap-2">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-mono text-xs font-bold text-amber-300 bg-slate-900 px-2 py-0.5 rounded border border-slate-700">
                        {item.clause.clause_id}
                      </span>
                      <span className="text-xs font-medium text-slate-200">
                        {item.clause.clause_category}
                      </span>
                      {(() => {
                        const tone = getClauseToneSentiment(item.clause);
                        return (
                          <span
                            data-testid="dossier-clause-sentiment-badge"
                            className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold border ${tone.badge}`}
                            title={tone.tooltip}
                          >
                            <span className={`w-1 h-1 rounded-full ${tone.dot}`} />
                            {tone.sentiment === 'Assertive' && <Flame className="w-2.5 h-2.5 text-purple-400 shrink-0" />}
                            {tone.sentiment === 'Protective' && <Shield className="w-2.5 h-2.5 text-sky-400 shrink-0" />}
                            {tone.sentiment === 'Neutral' && <Scale className="w-2.5 h-2.5 text-slate-400 shrink-0" />}
                            <span>{tone.label}</span>
                          </span>
                        );
                      })()}
                    </div>

                    <div className="flex items-center gap-1.5">
                      {onUpdatePriority && (
                        <select
                          aria-label={`Update priority for ${item.clauseId}`}
                          value={item.priority}
                          onChange={(e) => onUpdatePriority(item.clauseId, e.target.value as DossierPriority)}
                          className="bg-slate-900 border border-slate-700 text-slate-300 text-[11px] font-semibold rounded px-2 py-0.5 focus:ring-1 focus:ring-amber-500 focus:outline-hidden cursor-pointer"
                        >
                          <option value="HIGH_PRIORITY">🔥 High Priority</option>
                          <option value="WALKAWAY">⛔ Walkaway</option>
                          <option value="CLARIFY">❓ Clarify</option>
                          <option value="REDLINE">✍️ Redline</option>
                        </select>
                      )}

                      {onRemoveItem && (
                        <button
                          type="button"
                          onClick={() => onRemoveItem(item.clauseId)}
                          className="p-1 text-slate-500 hover:text-red-400 transition cursor-pointer"
                          title="Remove from curated dossier"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      )}
                    </div>
                  </div>

                  <div className="bg-slate-900/50 rounded p-2.5 border border-slate-800 text-xs font-serif italic text-slate-300 line-clamp-2">
                    "{item.clause.verbatim_quote}"
                  </div>

                  <p className="text-xs text-slate-400 line-clamp-2">
                    {item.clause.plain_english_meaning}
                  </p>
                </div>

                {/* Consultation Objective & Actions */}
                <div className="pt-2 border-t border-slate-800/80 space-y-2">
                  <div className="flex items-center justify-between text-[11px]">
                    <span className="text-indigo-300 font-semibold flex items-center gap-1">
                      <MessageSquare className="w-3 h-3 text-indigo-400" />
                      Client Consultation Note:
                    </span>
                    {onUpdateNote && editingNoteId !== item.clauseId && (
                      <button
                        type="button"
                        onClick={() => {
                          setEditingNoteId(item.clauseId);
                          setTempNote(item.customNote || '');
                        }}
                        className="text-[10px] text-amber-400 hover:underline cursor-pointer"
                      >
                        {item.customNote ? 'Edit' : '+ Add Note'}
                      </button>
                    )}
                  </div>

                  {editingNoteId === item.clauseId ? (
                    <div className="space-y-1.5">
                      <textarea
                        value={tempNote}
                        onChange={(e) => setTempNote(e.target.value)}
                        placeholder="What specific outcome or advice do you need for this clause?..."
                        className="w-full bg-slate-900 border border-indigo-500/50 rounded p-2 text-xs text-slate-200 placeholder-slate-500 focus:outline-hidden"
                        rows={2}
                      />
                      <div className="flex items-center justify-end gap-2">
                        <button
                          type="button"
                          onClick={() => setEditingNoteId(null)}
                          className="px-2 py-0.5 text-xs text-slate-400 hover:text-slate-200 cursor-pointer"
                        >
                          Cancel
                        </button>
                        <button
                          type="button"
                          onClick={() => {
                            if (onUpdateNote) onUpdateNote(item.clauseId, tempNote);
                            setEditingNoteId(null);
                          }}
                          className="px-2.5 py-0.5 rounded bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold cursor-pointer"
                        >
                          Save
                        </button>
                      </div>
                    </div>
                  ) : item.customNote ? (
                    <p className="text-xs text-indigo-200 bg-indigo-950/30 border border-indigo-500/20 rounded p-2">
                      "{item.customNote}"
                    </p>
                  ) : (
                    <p className="text-[11px] text-slate-500 italic">
                      No client note added. Click "+ Add Note" to specify objectives for counsel.
                    </p>
                  )}

                  {onNavigateToClause && (
                    <div className="flex justify-end pt-1">
                      <button
                        type="button"
                        onClick={() => onNavigateToClause(item.clauseId)}
                        className="text-[11px] text-amber-400 hover:text-amber-300 transition cursor-pointer flex items-center gap-1 hover:underline"
                      >
                        <span>Inspect in Clause Cards</span>
                        <ArrowRight className="w-3 h-3" />
                      </button>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* 1. Top Red Flags */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
        <div className="flex items-center gap-2">
          <AlertOctagon className="w-4 h-4 text-red-400" />
          <h4 className="text-sm font-semibold uppercase tracking-wider text-red-400 font-sans">
            Top Priority Red Flags for Legal Review
          </h4>
        </div>
        <div className="space-y-2.5">
          {dossier.top_red_flags_for_discussion.map((flag, idx) => (
            <div
              key={idx}
              className="p-3 rounded-lg bg-slate-950/70 border border-red-500/20 text-xs text-slate-200 flex items-start gap-3"
            >
              <span className="w-5 h-5 rounded-full bg-red-500/20 text-red-300 font-mono font-bold flex items-center justify-center shrink-0 mt-0.5">
                {idx + 1}
              </span>
              <span className="leading-relaxed font-sans">{flag}</span>
            </div>
          ))}
        </div>
      </div>

      {/* 2. High-Leverage Questions for Counsel */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <HelpCircle className="w-4 h-4 text-amber-400" />
            <h4 className="text-sm font-semibold uppercase tracking-wider text-amber-400 font-sans">
              High-Leverage Questions for Attorney Billing Session
            </h4>
          </div>
          <span className="text-[11px] text-slate-400">Click to copy individual question</span>
        </div>

        <div className="space-y-3">
          {dossier.high_leverage_questions_for_counsel.map((question, idx) => (
            <div
              key={idx}
              className="p-3.5 rounded-lg bg-slate-950/70 border border-slate-800 hover:border-slate-700 text-xs text-slate-200 flex items-start justify-between gap-4 transition group"
            >
              <div className="flex items-start gap-3">
                <span className="w-5 h-5 rounded-full bg-amber-500/20 text-amber-300 font-mono font-bold flex items-center justify-center shrink-0 mt-0.5">
                  Q{idx + 1}
                </span>
                <span className="leading-relaxed font-sans text-slate-100 font-medium">{question}</span>
              </div>

              <button
                id={`copy-q-${idx}`}
                onClick={() => handleCopyQuestion(question, idx)}
                className="opacity-80 group-hover:opacity-100 p-1.5 rounded hover:bg-slate-800 text-slate-400 hover:text-amber-300 transition cursor-pointer shrink-0"
                title="Copy Question"
              >
                {copiedQuestionIdx === idx ? (
                  <Check className="w-4 h-4 text-emerald-400" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* 3. Suggested Walkaway Terms */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
        <div className="flex items-center gap-2">
          <Ban className="w-4 h-4 text-rose-400" />
          <h4 className="text-sm font-semibold uppercase tracking-wider text-rose-400 font-sans">
            Recommended Walkaway Terms (Dealbreaker Thresholds)
          </h4>
        </div>
        <p className="text-xs text-slate-400">
          If the counterparty refuses to amend or strike these specific clauses, execution carries severe asymmetric operational risk.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {dossier.suggested_walkaway_terms.map((term, idx) => (
            <div
              key={idx}
              className="p-3.5 rounded-lg bg-slate-950/80 border border-rose-900/40 text-xs text-slate-200 flex items-start gap-2.5"
            >
              <span className="w-2 h-2 rounded-full bg-rose-500 mt-1.5 shrink-0" />
              <span className="leading-relaxed">{term}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Statutory Disclaimer Box */}
      <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-400 leading-relaxed text-center">
        <strong className="text-slate-300 block mb-1">Lexisense Statutory Boundary Notice</strong>
        {disclaimer}
      </div>
        </>
      )}
    </div>
  );
};
