/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CriticalClauseAudit } from '../types';

export type DossierPriority = 'HIGH_PRIORITY' | 'WALKAWAY' | 'CLARIFY' | 'REDLINE';

export interface PinnedDossierItem {
  clauseId: string;
  clause: CriticalClauseAudit;
  pinnedAt: number;
  priority: DossierPriority;
  customNote?: string;
  workingRedline?: string;
}

const STORAGE_PREFIX = 'lexisense_pinned_dossier_';
const inMemoryCache: Record<string, Record<string, PinnedDossierItem>> = {};

/**
 * Load pinned dossier collection from session storage
 */
export function loadPinnedDossier(docTitle: string = 'default'): Record<string, PinnedDossierItem> {
  try {
    if (typeof window !== 'undefined' && window.sessionStorage) {
      const raw = window.sessionStorage.getItem(`${STORAGE_PREFIX}${encodeURIComponent(docTitle)}`);
      if (raw) return JSON.parse(raw);
    }
  } catch (err) {
    console.warn('Failed to load pinned dossier items from sessionStorage:', err);
  }
  return inMemoryCache[docTitle] ? { ...inMemoryCache[docTitle] } : {};
}

/**
 * Persist pinned dossier collection to session storage
 */
export function savePinnedDossier(docTitle: string = 'default', items: Record<string, PinnedDossierItem>): void {
  inMemoryCache[docTitle] = { ...items };
  try {
    if (typeof window !== 'undefined' && window.sessionStorage) {
      window.sessionStorage.setItem(`${STORAGE_PREFIX}${encodeURIComponent(docTitle)}`, JSON.stringify(items));
    }
  } catch (err) {
    console.warn('Failed to save pinned dossier items to sessionStorage:', err);
  }
}

/**
 * Toggle pin status for a clause
 */
export function togglePinClause(
  current: Record<string, PinnedDossierItem>,
  clause: CriticalClauseAudit,
  workingRedline?: string
): { updated: Record<string, PinnedDossierItem>; wasPinned: boolean } {
  const updated = { ...current };
  if (updated[clause.clause_id]) {
    delete updated[clause.clause_id];
    return { updated, wasPinned: false };
  } else {
    updated[clause.clause_id] = {
      clauseId: clause.clause_id,
      clause,
      pinnedAt: Date.now(),
      priority: clause.risk_level === 'CRITICAL' ? 'HIGH_PRIORITY' : 'CLARIFY',
      workingRedline: workingRedline || clause.proposed_redline
    };
    return { updated, wasPinned: true };
  }
}

/**
 * Update custom consultation note for a pinned item
 */
export function updatePinnedItemNote(
  current: Record<string, PinnedDossierItem>,
  clauseId: string,
  note: string
): Record<string, PinnedDossierItem> {
  if (!current[clauseId]) return current;
  return {
    ...current,
    [clauseId]: {
      ...current[clauseId],
      customNote: note
    }
  };
}

/**
 * Update consultation priority for a pinned item
 */
export function updatePinnedItemPriority(
  current: Record<string, PinnedDossierItem>,
  clauseId: string,
  priority: DossierPriority
): Record<string, PinnedDossierItem> {
  if (!current[clauseId]) return current;
  return {
    ...current,
    [clauseId]: {
      ...current[clauseId],
      priority
    }
  };
}

/**
 * Remove an item from the pinned collection
 */
export function removePinnedItem(
  current: Record<string, PinnedDossierItem>,
  clauseId: string
): Record<string, PinnedDossierItem> {
  const updated = { ...current };
  delete updated[clauseId];
  return updated;
}

/**
 * Generates formatted Markdown brief for curated consultation items
 */
export function exportCuratedDossierMarkdown(
  items: PinnedDossierItem[],
  docTitle: string = 'Contract Instrument',
  dfiScore: number = 50
): string {
  const dateStr = new Date().toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric'
  });

  const lines: string[] = [
    `# CURATED ATTORNEY CONSULTATION DOSSIER`,
    `Generated by Lexisense Legal Intelligence Engine`,
    `Date: ${dateStr}`,
    `Document: ${docTitle}`,
    `Document Fairness Index (DFI): ${dfiScore}/100`,
    `Total Curated Clauses for Review: ${items.length}`,
    '',
    `## EXECUTIVE SUMMARY FOR COUNSEL`,
    `The client has curated ${items.length} pivotal clauses from "${docTitle}" requiring targeted legal review, negotiation counsel, and walkaway threshold validation.`,
    ''
  ];

  items.forEach((item, idx) => {
    const priorityLabel = 
      item.priority === 'HIGH_PRIORITY' ? '🔥 HIGH PRIORITY' :
      item.priority === 'WALKAWAY' ? '⛔ DEALBREAKER / WALKAWAY' :
      item.priority === 'REDLINE' ? '✍️ REDLINE COUNTER-OFFER' :
      '❓ CLARIFICATION NEEDED';

    lines.push(`### ${idx + 1}. [${item.clause.clause_id}] ${item.clause.clause_category}`);
    lines.push(`- **Consultation Priority**: ${priorityLabel}`);
    lines.push(`- **Risk Tier**: ${item.clause.risk_level} (Favors: ${item.clause.party_favored})`);
    
    if (item.customNote && item.customNote.trim()) {
      lines.push(`- **Client Consultation Objective**: "${item.customNote.trim()}"`);
    }

    lines.push(`- **Plain-English Impact**: ${item.clause.plain_english_meaning}`);
    lines.push(`- **Verbatim Clause Extract**:`);
    lines.push(`  > "${item.clause.verbatim_quote}"`);

    if (item.clause.hidden_pitfalls && item.clause.hidden_pitfalls.length > 0) {
      lines.push(`- **Hidden Pitfalls**:`);
      item.clause.hidden_pitfalls.forEach(p => {
        lines.push(`  - ${p}`);
      });
    }

    const proposed = item.workingRedline || item.clause.proposed_redline;
    lines.push(`- **Proposed Balanced Counter-Language**:`);
    lines.push(`  \`\`\``);
    lines.push(`  ${proposed}`);
    lines.push(`  \`\`\``);
    lines.push('');
  });

  lines.push('---');
  lines.push('*Disclaimer: This curated dossier is prepared for informational consultation purposes only to streamline communication with licensed legal counsel.*');

  return lines.join('\n');
}
