/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { SAMPLE_CONTRACTS } from './data/sampleContracts';
import { LexisenseAnalysisResult, SampleContract } from './types';
import { Header } from './components/Header';
import { FairnessGauge } from './components/FairnessGauge';
import { ClauseAuditList } from './components/ClauseAuditList';
import { WhatIfSimulator } from './components/WhatIfSimulator';
import { AttorneyDossier } from './components/AttorneyDossier';
import { DocumentModal } from './components/DocumentModal';
import { ExportModal } from './components/ExportModal';
import { SourceViewerModal } from './components/SourceViewerModal';
import { SplitViewAuditor } from './components/SplitViewAuditor';
import { 
  FileCheck, 
  Zap, 
  Briefcase, 
  FileText, 
  Sparkles, 
  Upload, 
  ShieldCheck, 
  Scale, 
  Layers,
  CheckCircle,
  ExternalLink,
  Info,
  Split,
  Crosshair
} from 'lucide-react';

export default function App() {
  // Initialize with the first sample contract (Enterprise Cloud SaaS MSA)
  const defaultSample = SAMPLE_CONTRACTS[0];
  const [analysis, setAnalysis] = useState<LexisenseAnalysisResult | null>(defaultSample.presetAnalysis || null);
  const [currentDocumentText, setCurrentDocumentText] = useState<string>(defaultSample.content);
  const [currentDocTitle, setCurrentDocTitle] = useState<string>(defaultSample.title);
  const [selectedSampleId, setSelectedSampleId] = useState<string>(defaultSample.id);

  // Modals & UI states
  const [activeTab, setActiveTab] = useState<'split' | 'clauses' | 'stress' | 'dossier'>('split');
  const [isDocModalOpen, setIsDocModalOpen] = useState<boolean>(false);
  const [isExportModalOpen, setIsExportModalOpen] = useState<boolean>(false);
  const [isSourceModalOpen, setIsSourceModalOpen] = useState<boolean>(false);
  const [isAnalyzing, setIsAnalyzing] = useState<boolean>(false);
  const [analysisError, setAnalysisError] = useState<string | null>(null);
  const [copiedDossier, setCopiedDossier] = useState<boolean>(false);

  // Handle selecting one of the pre-loaded benchmark contracts
  const handleSelectSample = (sample: SampleContract) => {
    setSelectedSampleId(sample.id);
    setCurrentDocumentText(sample.content);
    setCurrentDocTitle(sample.title);
    if (sample.presetAnalysis) {
      setAnalysis(sample.presetAnalysis);
    }
    setAnalysisError(null);
  };

  // Handle analyzing custom text via Gemini backend
  const handleAnalyzeDocument = async (text: string, title: string, perspective: string) => {
    setIsAnalyzing(true);
    setAnalysisError(null);

    try {
      const response = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          documentText: text,
          perspective
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `Server returned error ${response.status}`);
      }

      const result: LexisenseAnalysisResult = await response.json();
      setAnalysis(result);
      setCurrentDocumentText(text);
      setCurrentDocTitle(title || result.document_overview.document_title);
      setSelectedSampleId('');
      setIsDocModalOpen(false);
      setActiveTab('clauses');
    } catch (err: any) {
      console.error('Lexisense Analysis Failure:', err);
      setAnalysisError(err.message || 'Failed to complete document deconstruction.');
    } finally {
      setIsAnalyzing(false);
    }
  };

  // Quick copy attorney briefing
  const handleCopyDossier = () => {
    if (!analysis) return;
    const dossier = analysis.lawyer_consultation_dossier;
    const brief = `# ATTORNEY CONSULTATION BRIEFING
Generated by Lexisense Legal Intelligence Engine
Document: ${analysis.document_overview.document_title}
Document Fairness Index (DFI): ${analysis.document_overview.fairness_index}/100

## TOP RED FLAGS FOR DISCUSSION
${dossier.top_red_flags_for_discussion.map((rf, i) => `${i + 1}. ${rf}`).join('\n')}

## HIGH-LEVERAGE QUESTIONS FOR COUNSEL
${dossier.high_leverage_questions_for_counsel.map((q, i) => `${i + 1}. ${q}`).join('\n')}

## SUGGESTED WALKAWAY TERMS
${dossier.suggested_walkaway_terms.map((w, i) => `- ${w}`).join('\n')}

---
${analysis.statutory_disclaimer}
`;
    navigator.clipboard.writeText(brief);
    setCopiedDossier(true);
    setTimeout(() => setCopiedDossier(false), 2000);
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans">
      {/* Top Navigation */}
      <Header
        onOpenNewAnalysis={() => setIsDocModalOpen(true)}
        onOpenExportModal={() => setIsExportModalOpen(true)}
        onCopyDossier={handleCopyDossier}
        copiedDossier={copiedDossier}
        hasAnalysis={!!analysis}
        analysis={analysis}
        activeDocTitle={currentDocTitle}
      />

      {/* Benchmark Selector Bar */}
      <div className="bg-slate-900/60 border-b border-slate-800 px-4 sm:px-6 lg:px-8 py-2.5">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row sm:items-center justify-between gap-2.5">
          <div className="flex items-center gap-2 overflow-x-auto py-1 scrollbar-none">
            <span className="text-xs text-slate-400 font-semibold uppercase tracking-wider shrink-0 flex items-center gap-1">
              <Layers className="w-3.5 h-3.5 text-amber-400" />
              Benchmarks:
            </span>
            {SAMPLE_CONTRACTS.map(sample => (
              <button
                key={sample.id}
                onClick={() => handleSelectSample(sample)}
                className={`text-xs px-3 py-1 rounded-full whitespace-nowrap font-medium transition cursor-pointer shrink-0 border ${
                  selectedSampleId === sample.id
                    ? 'bg-amber-500/20 text-amber-300 border-amber-500/50 shadow-sm'
                    : 'bg-slate-800/80 hover:bg-slate-800 text-slate-300 border-slate-700'
                }`}
              >
                {sample.title}
              </button>
            ))}
          </div>

          <div className="flex items-center gap-3 shrink-0 self-end sm:self-auto">
            <button
              onClick={() => setIsSourceModalOpen(true)}
              className="text-xs text-slate-400 hover:text-amber-300 flex items-center gap-1.5 transition cursor-pointer"
            >
              <FileText className="w-3.5 h-3.5 text-amber-400" />
              <span>View Source Text</span>
            </button>
          </div>
        </div>
      </div>

      {/* Main Content Area */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">
        {analysis ? (
          <>
            {/* 1. Document Overview & Document Fairness Index Gauge */}
            <FairnessGauge
              overview={analysis.document_overview}
              clauses={analysis.critical_clause_audit}
            />

            {/* 2. Interactive Navigation Tabs */}
            <div className="border-b border-slate-800 flex items-center justify-between flex-wrap gap-2">
              <nav className="flex space-x-1 sm:space-x-4">
                <button
                  id="tab-split"
                  onClick={() => setActiveTab('split')}
                  className={`py-3 px-3 text-xs sm:text-sm font-semibold border-b-2 flex items-center gap-2 transition cursor-pointer ${
                    activeTab === 'split'
                      ? 'border-amber-500 text-amber-400'
                      : 'border-transparent text-slate-400 hover:text-slate-200'
                  }`}
                >
                  <Split className="w-4 h-4 text-amber-400" />
                  <span>Dual-Pane Citation Inspector</span>
                  <span className="ml-1 px-1.5 py-0.2 rounded-full text-[10px] bg-emerald-950 text-emerald-300 border border-emerald-800/60">
                    Ground Truth
                  </span>
                </button>

                <button
                  id="tab-clauses"
                  onClick={() => setActiveTab('clauses')}
                  className={`py-3 px-3 text-xs sm:text-sm font-semibold border-b-2 flex items-center gap-2 transition cursor-pointer ${
                    activeTab === 'clauses'
                      ? 'border-amber-500 text-amber-400'
                      : 'border-transparent text-slate-400 hover:text-slate-200'
                  }`}
                >
                  <FileCheck className="w-4 h-4" />
                  <span>Clause Audit Cards</span>
                  <span className="ml-1 px-1.5 py-0.2 rounded-full text-[10px] bg-slate-800 text-slate-300">
                    {analysis.critical_clause_audit.length}
                  </span>
                </button>

                <button
                  id="tab-stress"
                  onClick={() => setActiveTab('stress')}
                  className={`py-3 px-3 text-xs sm:text-sm font-semibold border-b-2 flex items-center gap-2 transition cursor-pointer ${
                    activeTab === 'stress'
                      ? 'border-amber-500 text-amber-400'
                      : 'border-transparent text-slate-400 hover:text-slate-200'
                  }`}
                >
                  <Zap className="w-4 h-4 text-amber-400" />
                  <span>"What-If" Stress-Tests</span>
                  <span className="ml-1 px-1.5 py-0.2 rounded-full text-[10px] bg-slate-800 text-slate-300">
                    {analysis.what_if_stress_tests.length}
                  </span>
                </button>

                <button
                  id="tab-dossier"
                  onClick={() => setActiveTab('dossier')}
                  className={`py-3 px-3 text-xs sm:text-sm font-semibold border-b-2 flex items-center gap-2 transition cursor-pointer ${
                    activeTab === 'dossier'
                      ? 'border-amber-500 text-amber-400'
                      : 'border-transparent text-slate-400 hover:text-slate-200'
                  }`}
                >
                  <Briefcase className="w-4 h-4 text-indigo-400" />
                  <span>Attorney Dossier</span>
                  <span className="ml-1 px-1.5 py-0.2 rounded-full text-[10px] bg-indigo-950/80 text-indigo-300 border border-indigo-800/60">
                    High Leverage
                  </span>
                </button>
              </nav>

              <div className="hidden sm:flex items-center gap-2 text-xs text-slate-400">
                <span className="inline-flex items-center gap-1 text-[11px] text-emerald-400/90 font-mono">
                  <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                  100% Verbatim Ground Truth Active
                </span>
              </div>
            </div>

            {/* Tab Views */}
            <div>
              {activeTab === 'split' && (
                <SplitViewAuditor
                  documentText={currentDocumentText}
                  clauses={analysis.critical_clause_audit}
                />
              )}

              {activeTab === 'clauses' && (
                <ClauseAuditList
                  clauses={analysis.critical_clause_audit}
                  documentText={currentDocumentText}
                  onLocateInSource={(clauseId) => {
                    setActiveTab('split');
                  }}
                />
              )}

              {activeTab === 'stress' && (
                <WhatIfSimulator
                  tests={analysis.what_if_stress_tests}
                  documentText={currentDocumentText}
                />
              )}

              {activeTab === 'dossier' && (
                <AttorneyDossier
                  dossier={analysis.lawyer_consultation_dossier}
                  docTitle={analysis.document_overview.document_title}
                  fairnessIndex={analysis.document_overview.fairness_index}
                  disclaimer={analysis.statutory_disclaimer}
                />
              )}
            </div>
          </>
        ) : (
          /* Empty State when no document loaded */
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-12 text-center max-w-2xl mx-auto space-y-6">
            <div className="w-16 h-16 rounded-2xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-center text-amber-400 mx-auto">
              <Scale className="w-8 h-8" />
            </div>
            <div className="space-y-2">
              <h3 className="text-xl font-bold text-white font-['Cinzel',serif]">
                No Instrument Currently Loaded
              </h3>
              <p className="text-sm text-slate-400 max-w-md mx-auto leading-relaxed">
                Ingest any contract, service agreement, lease, or NDA to activate the Lexisense legal deconstruction engine.
              </p>
            </div>
            <button
              onClick={() => setIsDocModalOpen(true)}
              className="px-6 py-2.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 text-sm font-bold shadow-md transition cursor-pointer"
            >
              Analyze Contract Now
            </button>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-800/80 bg-slate-950 py-4 px-4 sm:px-6 lg:px-8 text-center text-xs text-slate-400">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <Scale className="w-3.5 h-3.5 text-amber-400" />
            <span className="font-semibold text-slate-300">Lexisense Legal Intelligence & Document Deconstruction</span>
          </div>
          <p className="text-[11px] text-slate-400">
            Automated Legal Intelligence Engine • Strictly Citation Locked • For Educational & Preparatory Purposes
          </p>
        </div>
      </footer>

      {/* Modals */}
      <DocumentModal
        isOpen={isDocModalOpen}
        onClose={() => setIsDocModalOpen(false)}
        onAnalyze={handleAnalyzeDocument}
        onSelectSample={handleSelectSample}
        isAnalyzing={isAnalyzing}
        error={analysisError}
      />

      <ExportModal
        isOpen={isExportModalOpen}
        onClose={() => setIsExportModalOpen(false)}
        analysis={analysis}
      />

      <SourceViewerModal
        isOpen={isSourceModalOpen}
        onClose={() => setIsSourceModalOpen(false)}
        title={currentDocTitle}
        content={currentDocumentText}
      />
    </div>
  );
}
